### ISSUE TITLE
Model Research

### ISSUE THREAD

**Issue by ajhaller** [busi732/Team-2-2024Fall#10]
**Objective**
Develop a model that recommends the type of maintenance (internal or external vendor) required for each fault type based on historical data. The model will aim to minimize maintenance costs by considering both internal and external maintenance options and adjusting for seasonal cost variations.

As the data science team, we want to build a model that determines the most cost-effective maintenance approach (internal or external vendor) when a particular fault occurs. By leveraging historical data on fault types, maintenance costs, and seasonal demand variations, we aim to provide actionable recommendations that optimize maintenance costs while ensuring reliable turbine operations.

**Data Analysis**

- Analyze historical data to identify common fault types and associated maintenance needs.
- Review the seasonal patterns to define "Normal Season" and "High Energy Demand Season."
- Summarize findings on fault occurrences, maintenance costs, and seasonality to inform model development.
- Predictive Maintenance Recommendation Model Development

**Develop a model that, based on a specific fault occurrence, recommends either:**
- Internal Maintenance (fixed annual cost of $750,000 per fault type) or
- External Vendor Maintenance with:
- Normal Season Cost: $50,000 per trip
- High Energy Demand Season Cost: $150,000 per trip.
- Ensure the model considers seasonal variations in external vendor costs and selects the option with the lowest cost per maintenance event.

**Cost Optimization**
- Integrate the cost parameters into the model so it can dynamically choose the more cost-effective maintenance option based on the season and the fault type.
- Calculate cost savings achieved by the model's recommendations over a specified period.

**Validation of Model**
- Validate the model by comparing its recommendations with actual historical maintenance decisions and their costs.
- Achieve a threshold of at least 90% accuracy in recommending the optimal maintenance type.

**Final Deliverables**
- Provide a fully functional predictive maintenance recommendation model.
- Document the assumptions, logic, and interpretation of model outputs for use in maintenance decision-making.
- Summarize findings and model recommendations, highlighting potential cost savings, optimized maintenance practices, and seasonal insights.

**Comment by rr-85** [comment]
The merged dataset appears to be extensive, containing columns on fault occurrences, weather conditions, turbine status, and various operational parameters. Given this, here are some data science approaches for optimizing predictive maintenance:

**Random Forest Regression (Predictive Modeling)**

Purpose: Use this model to predict the likelihood and timing of faults based on historical data.
Pros: Handles mixed data types and provides feature importance, highlighting which parameters influence fault occurrence most.
Cons: Computationally intensive; may require tuning to prevent overfitting.
Fit with Data: Random Forest models perform well on time-series or event-driven data like fault records, making it useful for interpreting the relationship between weather, operational conditions, and fault occurrences.
Gradient Boosting Machines (GBM)

Purpose: Optimize the timing of maintenance actions by predicting fault risks and prioritizing which faults to address.
Pros: GBMs excel in capturing complex patterns; can be used to create probabilistic predictions for fault likelihood.
Cons: Requires tuning and may overfit on smaller datasets.
Fit with Data: Effective for datasets with multiple features influencing outcomes, such as energy production and fault metrics.

**Markov Decision Process (MDP) for Maintenance Scheduling Optimization**

Purpose: To create a strategy that minimizes maintenance costs while maximizing uptime, considering the variable cost of in-house vs. external maintenance.
Pros: Considers sequential decision-making; can optimize costs by balancing preventative maintenance and repair.
Cons: Requires assumptions about state transitions and fault frequencies.
Fit with Data: MDP is suitable for data with state-based transitions, like turbine operational states and maintenance options.

**Reinforcement Learning (RL) for Preventative vs. Reactive Maintenance Strategy**

Purpose: Develop a dynamic policy to determine whether to conduct preventative maintenance based on evolving conditions.
Pros: RL adapts to new data, allowing the model to optimize decisions based on ongoing operations.
Cons: Needs significant data and computational resources; may be complex to set up.
Fit with Data: RL fits well with continuous decision-making processes in variable environments, like adjusting for fluctuating weather and production needs

**Comment by rr-85** [comment]
**Independent**
The model development is a self-contained task that relies only on historical fault and maintenance data, which we already have. It does not depend on other teams' work.

**Negotiable**
While the primary goal is cost optimization, there may be flexibility in adjusting model constraints (e.g., accuracy threshold, preventive success rate) as needed to align with evolving business objectives.

**Valuable**
This model will provide valuable, actionable insights for the operations team, allowing for cost-effective maintenance planning that maximizes turbine uptime, particularly during high energy demand periods.

**Estimable**
The project scope is well-defined, with clear requirements for the data analysis, cost optimization, and validation steps, making it possible to estimate time and resource needs accurately.

**Small**
The model is divided into manageable phases: data analysis, model development with Pyomo and Gurobi, cost optimization, and validation, allowing incremental progress.

**Testable**
The model's effectiveness will be validated by comparing its recommendations to historical maintenance decisions and measuring cost savings and accuracy (target: at least 90% accuracy).

**Comment by rr-85** [comment]
As a data science team, we want to build a model that uses an objective function to determine the most cost-effective maintenance strategy (internal or external vendor) for each fault type, taking seasonal variations into account, So that we can minimize overall maintenance costs and maximize turbine uptime.

**1) Objective Function Development**
- Use Pyomo to define an objective function that minimizes total maintenance costs by choosing between internal and external vendor options based on seasonal cost variations.

**2) Implementation with Gurobi Solver**
- Apply the Gurobi solver in Pyomo to optimize the objective function, ensuring it selects the most cost-effective maintenance strategy for each fault type.
-
**3) Data Analysis and Cost Calculation**
- Conduct data analysis to identify fault types, maintenance costs, and seasonal patterns.**
- Define cost parameters (internal and external) based on historical data and seasonal fluctuations.

**4) Model Constraints and Variables**

**Integrate constraints for failure prevention, production uptime, and budget.**
- Define variables including internal/external maintenance actions, failure rates, and costs.

**5) Seasonal Cost Adjustment**
- Ensure the model dynamically adjusts for high-demand and normal seasons in external vendor costs.

**6) Cost Optimization and Savings Calculation**
- Calculate total cost savings generated by the model recommendations compared to current maintenance decisions.

The Objective function to solve and their constraints 
- https://github.com/busi732/Team-2-2024Fall/issues/14
- If our Objective function to solve and their constraints are accurate, we will begin implementation of the function with Gurobi Solver in python to find an optimal solution.

**Comment by rr-85** [comment]
@gibby-ci Please provide feedback, on writing the user story and our current understanding of the modeling
