### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by ajhaller** [busi732/Team-2-2024Fall#13]
### Objective

As a data scientist, I want to create an ERD diagram to visualize our raw data schema, allowing us to understand how to use our data and for new repo viewers to understand our data better.

### Acceptance Criteria

- Add fault, SCADA, and status raw data table
- Add merged (fault and SCADA) data table
- Add ERCOT market data table?

**Comment by JavierACM** [comment]
![Image](https://github.com/user-attachments/assets/cbdbe48a-2896-483b-8556-f88ed623dc9a)

I have completed draft 1 of the raw data schema ERD. How do you think I should proceed? Or is it ready to be published in the repo?

@ntuziyihuang @rr-85

**Comment by JavierACM** [comment]
I added a new "Calendar" table and committed the Status table as per the last team meeting since we won't use it for our model. Please let me know if you want to see something else or if I need to change anything before committing to our repo. @ntuziyihuang @rr-85 @gibby-ci 

![Image](https://github.com/user-attachments/assets/14ee0835-4fd2-4d2c-9c92-b5819beeb205)

**Comment by JavierACM** [comment]
@gibby-ci Thank you! I just created a user story on this ticket.

**Comment by JavierACM** [comment]
To-Do:

- Include the status raw data table, even though we won't be using it for our model
- Test if fault and SCADA tables have a one-to-one join relationship
    - If YES, delete the Calendar table because we'll be adding Date and Month columns to the merged table
    - If NO, keep the Calendar table to reduce redundancy
