### ISSUE TITLE
Identify Constraints & Variables

### ISSUE THREAD

**Issue by ajhaller** [busi732/Team-2-2024Fall#14]
**Objective**  
Identify the key constraints and variables necessary to formulate the objective function for optimizing the Wind Turbine Maintenance strategy. This will provide a foundation for developing a model that balances maintenance costs with maximizing uptime and energy production.

As the data science and optimization team, we need to define the constraints and variables for our objective function so that we can accurately model the decision-making process for turbine maintenance. By clearly outlining these elements, we aim to ensure that the model effectively minimizes maintenance costs while meeting operational requirements and managing resource limitations.

---

**Acceptance Criteria**

1. **Identify Variables**
   - Define decision variables that will influence the objective function, such as:
     - Type of maintenance (internal or external) for each fault type.
     - Timing of maintenance (normal season vs. high energy demand season).
     - Maintenance frequency for each fault type.
   - Ensure variables align with available data and project goals.

2. **Define Constraints**
   - Outline constraints that affect the maintenance scheduling and resource allocation, including:
     - Budget limitations for both internal and external maintenance.
     - Seasonal cost variations (e.g., higher costs during high energy demand season for external vendors).
     - Maximum allowable downtime for turbines to meet operational targets.
     - Resource limitations (e.g., availability of in-house maintenance teams vs. external vendors).
   - Ensure constraints are realistic and based on project and operational requirements.

3. **Objective Function Formulation**
   - Based on the defined variables and constraints, draft a preliminary objective function that:
     - Minimizes the total maintenance cost by choosing between internal and external options.
     - Accounts for seasonal cost differences and prioritizes cost-effective solutions.
   - Confirm that the objective function aligns with the overall project goal of maximizing turbine uptime and optimizing maintenance expenses.

**Comment by ntuziyihuang** [comment]
I did my research I wrote down the optimization function and our constraints, but I am not sure where this should be placed? For my understanding, this is more like the work followed by HDD. And if I only updating the file, without any manipulation of the code, should I also PR and merge? @gibby-ci

**Comment by ntuziyihuang** [comment]
### Objective Function

We aim to **minimize the total cost** of maintenance and failures, deciding between **internal** and **external** maintenance. Internal maintenance, while more expensive per instance, offers a higher preventive success rate. External maintenance, on the other hand, is less costly during normal periods but becomes more expensive in high-demand seasons. Our goal is to balance total cost, preventive effectiveness, and operational impact.

### Variables

#### Costs
* **Internal Maintenance Cost:** $C_{\text{internal}} $= \$750,000 per fault type
* **External Maintenance Cost:**
  * Normal Season: $C_{\text{external normal}}$ = \$50,000 per trip
  * High Demand Season: $C_{\text{external high demand}}$ = \$150,000 per trip

#### Decision Variables
* $x_{\text{internal}}$: Number of internal maintenance actions
* $x_{\text{external normal}}$: Number of external maintenance actions in normal seasons
* $x_{\text{external high demand}}$: Number of external maintenance actions in high-demand seasons

#### Additional Parameters
* **Preventive Success Rate:** $p_{\text{internal}} = 60\%$ for internal maintenance
* **Failure Cost:** $D_{\text{failure}}$: Downtime cost per failure 
* **Failure Frequency:** $F_{\text{freq}}$: Frequency of preventable faults
* **Production Requirement:** $U_{\text{required}}$: Required uptime

### Objective Function

To minimize total cost, we aim to:

$$
\text{Minimize } \text{TotalCost} = C_{\text{internal}} \cdot x_{\text{internal}} + C_{\text{external normal}} \cdot x_{\text{external normal}} + C_{\text{external high demand}} \cdot x_{\text{external high demand}} + D_{\text{failure}} \cdot F_{\text{occur}}
$$

where $F_{\text{occur}}$ is the number of failures due to unprevented issues.

### Constraints

1. **Failure Prevention Model:**
   Each internal maintenance action reduces failures by 60%:

   $$F_{\text{occur}} = F_{\text{freq}} \cdot (1 - 0.6 \cdot x_{\text{internal}})$$

2. **Uptime Constraint - Production:**
   Total downtime must not exceed the required uptime:

   $$T_{\text{total}} - T_{\text{down}} \geq T_{\text{required}}$$

3. **Budget Constraint:**
   Total maintenance cost cannot exceed the budget $B$:

   $$C_{\text{internal}} \cdot x_{\text{internal}} + C_{\text{external normal}} \cdot x_{\text{external normal}} + C_{\text{external high demand}} \cdot x_{\text{external high demand}} \leq B$$

4. **Non-Negativity Constraints:**
   All decision variables must be non-negative:
$$x_{\text{internal}} \geq 0, \quad x_{\text{external normal}} \geq 0, \quad x_{\text{external high demand}} \geq 0$$
