### ISSUE TITLE
ADR for ERD Tools

### ISSUE THREAD

**Issue by ajhaller** [busi732/Team-2-2024Fall#15]
### Objective

I want to create an Entity-Relationship Diagram (ERD) for the raw input and final output data.

### Acceptance Criteria

- Use the ADR template
- Research at least three ERD tools
- Have references to call back to
- Gain knowledge of chosen ERD tool

**Comment by JavierACM** [comment]
## **Table of Contents**
* [Intro](#Intro)
* [Context](#Context)
* [Decision](#Decision)
* [Consequences](#Consequences)
* [Implementation](#Implementation)
* [References](#References)
* [Revision History](#Revision-History)

## Intro
**Goal**: Make a knowledgeable choice between at least three different Entity-Relationship Diagram (ERD) tools.

**Date**: 2024-11-16

**Status**: Accepted

## Context
To better understand the data we have and the data we want, we must create an ERD diagram to show our dataset schemas. Creating an ERD allows new viewers to digest our data clearly and concisely.

## Decision
We chose to create our ERD diagrams using diagrams.net (formerly known as draw.io). This tool best fits our project because it doesn't limit how many objects we can have on a diagram and allows us to save and load our diagrams to cloud storage services.

Options:
- [dbdiagram.io](https://dbdiagram.io/home)
    - Free for up to 10 diagrams
    - $9/month after 10 diagrams
    - Uses their domain-specific language (DSL)
    - Real-time collaborative editing
    - Simple and neat UI
    - Diagram security options
- [diagrams.net](https://app.diagrams.net/)
    - Free for web-based usage
    - Allows saving to cloud storage services
    - Drag-and-drop UI
    - Visual interfaces are not as nice as Lucidchart
- [Lucidchart](https://www.lucidchart.com/pages/?)
    - Free with limited objects - 3 diagrams and 60 objects per diagram
    - $4.95-$9.00/user/month
    - Integrated with G Suite and MS Office
    - Cloud-based
    - Collaborative
    - Drag-and-drop UI
- [QuickDBD](https://www.quickdatabasediagrams.com/)
    - Free for 1 public diagram and 10 tables
    - $14 / month for unlimited tables and private diagrams
    - Draw diagrams using text input
    - Supports exporting to SQL, PDF, and Word

## Consequences
Every tool was limited to how much we could do except for diagrams.net. There's no limit to how many diagrams we could create or how many objects we could have in a diagram. We also like that we don't have to learn or use text commands to create tables, which we would've had to do if using dbdiagram.io and QuickDBD. Instead, we preferred a GUI for easier ERD modeling, although inferior to the GUI Lucidchart provides.

## Implementation
We will use diagrams.net to create ERD diagrams for our input raw and final output data.

## References
[Holistics - Top 10 Free Database Diagram Design Tools](https://www.holistics.io/blog/top-5-free-database-diagram-design-tools/)

## Revision History
2024-11-16 - Initial commit

**Comment by JavierACM** [comment]
Please let me know if you'd like me to change anything. @rr-85 @ntuziyihuang @ajhaller

**Comment by rr-85** [comment]
@JavierACM this is perfect, very detaile, the comparison is good and input ERD look good, please add to the wiki
